apiVersion: v1
kind: Service
metadata:
  name: counter-service
spec:
  selector:
    app: counter
  ports:
    - protocol: TCP
      port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: ticker-service
spec:
  selector:
    app: ticker
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30000

---

apiVersion: v1
kind: Pod
metadata:
  name: counter-pod
  labels:
    app: counter
spec:
  containers:
    - name: counter
      image: noobernetes_counter
      imagePullPolicy: Never
      ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Pod
metadata:
  name: ticker-pod
  labels:
    app: ticker
spec:
  containers:
    - name: ticker
      image: noobernetes_ticker
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
